FROM alpine

# crear carpeta 'carpeta'
RUN mkdir /carpeta

# crear archivo 'ejercicio1.txt' con el contenido 'Ejercicio 1'
RUN echo "Ejercicio 1" > /carpeta/ejercicio1.txt

# escribir por pantalla 'He acabado el ejercicio 1'
CMD ["echo", "He acabado el ejercicio 1"] 
